// DESIGN.md has one machine-readable form, in docs/tokens.json, and it is what both
// SDKs are tested against. This generates the TypeScript copy so the shipped package
// carries no path out of its own directory, and so a token cannot come to mean two
// different things on two platforms.
//
// Generated, not hand-maintained: a hand copy is a copy that drifts.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "docs", "tokens.json");
const target = join(here, "..", "src", "tokens.generated.ts");

const tokens = JSON.parse(readFileSync(source, "utf8"));
delete tokens.$comment;

const banner = `// Generated by scripts/sync-tokens.mjs from docs/tokens.json. Do not edit.
// Run \`npm run sync-tokens\` after changing DESIGN.md and docs/tokens.json.

`;
const body = `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`;

const next = banner + body;
let current = "";
try { current = readFileSync(target, "utf8"); } catch { /* first run */ }
if (current !== next) {
  writeFileSync(target, next);
  console.log("tokens.generated.ts written from docs/tokens.json");
}
