#!/usr/bin/env bash
#
# Regenerates CHANGELOG.md from the GitHub releases.
#
#   bash scripts/changelog.sh
#
# Generated rather than hand-written, and that is the point: the release notes are
# already written once, on the release, and a second copy maintained by hand goes
# stale the first time somebody is in a hurry. Edit the release on GitHub and run this
# again.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
out="$here/CHANGELOG.md"

{
  echo "# Changelog"
  echo
  echo "<!-- Generated by scripts/changelog.sh from the GitHub releases. Do not edit."
  echo "     Edit the release notes on GitHub and run the script again. -->"
  echo
  echo "Every release: <https://github.com/serhii-kucherenko/loupe/releases>"
  echo

  gh release list --limit 100 --json tagName --jq '.[].tagName' | while read -r tag; do
    date=$(gh release view "$tag" --json publishedAt --jq '.publishedAt' | cut -dT -f1)
    name=$(gh release view "$tag" --json name --jq '.name')
    echo "## [$tag](https://github.com/serhii-kucherenko/loupe/releases/tag/$tag) - $date"
    echo
    [ -n "$name" ] && { echo "**$name**"; echo; }
    gh release view "$tag" --json body --jq '.body'
    echo
  done

  # Tags that never got release notes. Named rather than omitted: a changelog that
  # silently starts at v0.1.3 reads as though nothing existed before it.
  released=$(gh release list --limit 100 --json tagName --jq '.[].tagName' | sort)
  tagged=$(git -C "$here" tag | sort)
  missing=$(comm -13 <(echo "$released") <(echo "$tagged"))
  if [ -n "$missing" ]; then
    echo "## Earlier tags"
    echo
    echo "Tagged, but with no release notes written at the time:"
    echo
    for tag in $missing; do
      date=$(git -C "$here" log -1 --format=%cs "$tag" 2>/dev/null || echo "")
      echo "- [\`$tag\`](https://github.com/serhii-kucherenko/loupe/releases/tag/$tag)${date:+ - $date}"
    done
    echo
  fi
} > "$out"

echo "wrote $out"
