// Generated by scripts/sync-tokens.mjs from docs/tokens.json. Do not edit.
// Run `npm run sync-tokens` after changing DESIGN.md and docs/tokens.json.

export const tokens = {
  "color": {
    "highlight": {
      "light": "#B5551D",
      "dark": "#E29A5A",
      "lightAlpha": 1,
      "darkAlpha": 1
    },
    "highlight.fill": {
      "light": "#B5551D",
      "dark": "#E29A5A",
      "lightAlpha": 0.1,
      "darkAlpha": 0.14
    },
    "surface": {
      "light": "#FFFFFF",
      "dark": "#141F1A",
      "lightAlpha": 0.92,
      "darkAlpha": 0.92
    },
    "ink": {
      "light": "#17211C",
      "dark": "#E9EFEA",
      "lightAlpha": 1,
      "darkAlpha": 1
    },
    "ink.soft": {
      "light": "#4C5A52",
      "dark": "#A2B2A8",
      "lightAlpha": 1,
      "darkAlpha": 1
    },
    "line": {
      "light": "#D6DED8",
      "dark": "#293830",
      "lightAlpha": 1,
      "darkAlpha": 1
    },
    "action": {
      "light": "#2F7D5B",
      "dark": "#62C68E",
      "lightAlpha": 1,
      "darkAlpha": 1
    },
    "scrim": {
      "light": "#17211C",
      "dark": "#000000",
      "lightAlpha": 0.08,
      "darkAlpha": 0.24
    }
  },
  "space": {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 24,
    "xxl": 32
  },
  "radius": {
    "panel": 16,
    "control": 10,
    "highlight": 6
  },
  "stroke": {
    "highlight": 2,
    "focus": 2,
    "focusOffset": 2,
    "hairline": 1
  },
  "elevation": {
    "panelRadius": 24,
    "panelOffsetY": 8,
    "panelOpacity": 0.18
  },
  "motion": {
    "hover": 90,
    "panel": 180,
    "commit": 220
  },
  "hit": {
    "touch": 44,
    "pointer": 28
  },
  "tag": {
    "bug": "highlight",
    "idea": "ink.soft",
    "polish": "ink.soft",
    "question": "action"
  }
} as const;
